# Generated by Django 2.2.11 on 2020-04-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pieza', models.CharField(max_length=50, unique=True)),
                ('prioridad', models.CharField(choices=[('Ba', 'Baja'), ('Me', 'Media'), ('Al', 'Alta')], default='Baja', max_length=10)),
                ('precio', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_edicion', models.DateField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='piezas.Categoria')),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
            },
        ),
    ]
