# Generated by Django 2.2.11 on 2020-04-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
        ('piezas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpieza',
            fields=[
                ('id_checkpieza', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_total', models.FloatField(blank=True, editable=False, null=True)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkpieza_pieza', to='piezas.Pieza')),
            ],
            options={
                'verbose_name': 'Checkpieza',
                'verbose_name_plural': 'Checkpiezas',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, max_length=150, null=True)),
                ('pieza', models.ManyToManyField(related_name='visita_piezas', through='checklist.Checkpieza', to='piezas.Pieza', verbose_name='piezas_chekc')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendas.Tienda')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.AddField(
            model_name='checkpieza',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkpieza_visita', to='checklist.Visita'),
        ),
    ]
