# Generated by Django 2.2.11 on 2020-04-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpieza',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='0'),
        ),
    ]
